/* Ask Wael: the answer bank.
   Work for employers is described in general terms only: nothing here should
   reveal an employer's or a customer's internal details.
   Each entry has a question, the words that should trigger it (k, a regular
   expression), optional other phrasings (also), and the answer (a).
   To add an answer, copy an entry and edit it. No server is involved. */
window.ASK_WAEL = [

/* ---------- about this page (first, so it wins a tie) ---------- */
{g:'About this page', id:'ai', q:'Is this an AI?', k:'are you (an? )?(ai|bot|robot|human|real)|is this (an? )?(ai|bot|chatbot)|am i talking|talking to (an? )?(ai|bot|human)|chatbot',
 a:"No. These are prepared answers that I wrote myself. The page looks for the closest one to your question; nothing is generated and nothing you type leaves your browser. If I miss, email me and I will answer in person."},

/* ---------- about me ---------- */
{g:'About me', id:'experience', q:'What is your experience?', k:'experien|background|career|about you|who are you|summary|introduce|yourself',
 also:['tell me about yourself','give me an overview of your career'],
 a:"I am a principal software engineer with more than fifteen years in C++ application and server-side software. I started in telecom billing at Openet, worked at L3Harris on aviation surveillance, led a team at Gibbs & Cox on an autonomous surface vessel, and since 2023 I lead the core network software at Elveo Mobile, which connects ordinary phones directly to satellites."},
{g:'About me', id:'years', q:'How many years of experience do you have?', k:'how many years|how long have you|years of experience|seniority',
 a:"More than fifteen years of professional software development, almost all of it in C++ on Linux, in domains where the software has to keep working: telecom, aviation, maritime and satellite."},
{g:'About me', id:'domains', q:'Which domains have you worked in?', k:'domain|industr|sector|field',
 a:"Four. Telecom mediation and billing for large carriers. Aviation surveillance: radar and ADS-B data, air traffic displays, tracking of unmanned aircraft. Maritime autonomy: the automation layer of an autonomous surface vessel. And satellite communications: the core network software for a satellite-to-phone service."},
{g:'About me', id:'fit', q:'What kind of work suits you best?', k:'best fit|suit|ideal (role|job|team)|kind of (work|role|team)|looking for|what do you want',
 a:"Software that other engineers and operators depend on: frameworks, tools, simulation and applications for systems that have to keep working. That has been the thread through my whole career, from telecom billing to satellites, and it is the work I enjoy most."},
{g:'About me', id:'proud', q:'What are you most proud of?', k:'proud|biggest (achievement|accomplishment)|best work|favorite project|favourite project',
 a:"A surveillance system I designed and built at L3Harris, from the first line: a framework of decoupled components on a thread pool, with features as steps and behavior driven by configuration. It was a new way of building for that department, and it was later adopted across its projects. I have applied the same approach since, to an autonomous vessel and to a satellite core network."},
{g:'About me', id:'turning', q:'What was the turning point in your career?', k:'turning point|changed your career|big break|milestone',
 a:"Being given a system of my own to build from scratch at L3Harris. It was the first time a design was mine from the first line. I built it on a thread pool and decoupled components, which was a new way of building for that department, and the approach was later adopted across its projects. It taught me that the way to change how a team builds is to build something that works."},
{g:'About me', id:'handson', q:'Do you prefer hands-on work or management?', k:'hands.?on|management|manager|individual contributor|still code|do you code',
 a:"Hands-on. I lead by designing and building: I set the architecture, write the core myself, and bring other engineers along on it. I have led a team and I mentor, but I am not looking to move away from the code."},
{g:'About me', id:'weakness', q:'What is a weakness of yours?', k:'weakness|weak point|improve about yourself|shortcoming|flaw',
 a:"I care a lot about design, and when I am convinced of an approach I can move ahead and build it before the team is with me. I have learned that a good design people did not choose is harder for them to own. So now I build a small working version first and bring people into the discussion early, around something they can run."},

/* ---------- how I work ---------- */
{g:'How I work', id:'approach', q:'How do you approach a project?', k:'approach|method|start a project|new project|how do you (work|build)|process',
 a:"In the same order every time. First the core libraries: the plugin framework, networking, a thread pool, configuration and logging. Then unit tests and code coverage. After that, one rule: anything added works through an abstraction that lives in its own library. And early on, a way to test without the real hardware."},
{g:'How I work', id:'philosophy', q:'What is your design philosophy?', k:'philosophy|principle|open.?closed|solid|architecture|design (style|approach)|how do you design',
 also:['how do you design software','what makes a good architecture'],
 a:"A stable core that does not change when features are added. The core handles loading, configuration, threading and data access behind abstractions, and each feature is added around it. That is the open/closed principle taken seriously: code that is already in service should not have to be edited to add something new."},
{g:'How I work', id:'plugin', q:'What is a plugin, in your view?', k:'what is a plugin|plugin (framework|architecture|design)|plugins',
 a:"A concrete implementation of an abstract concept that the core defines. You can replace one or add one to extend behavior, and nothing else changes. What a plugin should not be is the place where the main logic and its own threads live. Once plugins hold the core logic, they stop being interchangeable, and you have the complexity of plugins without the benefit."},
{g:'How I work', id:'whenplugins', q:'Is a plugin framework not over-engineering?', k:'over.?engineer|too complex|complexity|overkill|when (not )?to use',
 a:"For a small, stable system, yes. It pays for itself when the system runs in more than one environment, features keep arriving, and changing shipped code is risky. The complexity is paid once, in the core. After that, adding a feature is adding a library."},
{g:'How I work', id:'threadpool', q:'Why do you use thread pools?', k:'thread pool|threadpool|thread per|concurren|multithread|threads?\\b|parallel',
 a:"Because of the shape of the work in the systems I build: a continuous stream of small tasks of very different cost. A thread per feature gives a light task and a heavy task the same resources, and the features end up fighting over shared data. A pool shares a fixed set of workers across whatever is waiting, keeps each item's steps in order, and can be resized by configuration."},
{g:'How I work', id:'pool', q:'How do you handle database connections at scale?', k:'connection pool|session pool|scal(e|ab)|database connection|load',
 a:"With a session pool behind one abstract interface. A fixed set of connections is shared safely between threads, a caller waits when none is free, and the same pool works for PostgreSQL, MongoDB or SQLite. Load grows without a connection or a thread per request."},
{g:'How I work', id:'config', q:'How do you design configuration?', k:'configuration|config\\b|settings|configurable',
 a:"Each plugin owns its own small configuration class and registers it by name. A base class owns reading and validation, and a central registry stores the objects without knowing what is in them. So there is no single configuration class that every feature has to edit, and behavior such as the number of threads can be changed without touching code."},
{g:'How I work', id:'testing', q:'How do you approach testing?', k:'testing|unit test|coverage|gtest|gcov|tdd|quality|reliab',
 also:['how do you make sure your software is reliable','how do you ensure quality'],
 a:"Tests from the start, and honest ones. I add unit testing and code coverage as soon as the core exists, and I check that the tests can actually fail, because a test that cannot fail is worse than no test. I keep third-party code out of the coverage figures so the number means something. And I test under realistic conditions before it matters: an estimate is not a test."},
{g:'How I work', id:'improve', q:'What would you design differently today?', k:'differently|regret|redo|do over|change about your design|hindsight|singleton|dependency injection',
 a:"I have relied on global registries for things like configuration and connection pools. It is quick at the start, but it makes shutdown order fragile and components harder to unit test. Today I would inject those objects into each component when it is created. It is more typing, and both problems go away."},
{g:'How I work', id:'disagree', q:'How do you handle disagreement about a design?', k:'disagree|conflict|pushback|push back|convince|persuade|argument|different opinion',
 a:"I go to the person directly, with a concrete alternative, and I say what my own proposal gives up. Where I can, I keep their idea in the plan as a later step instead of trying to defeat it. And I have learned to show a small working version early: people judge something that runs much faster than a proposal. Once a decision is made, I build it properly, whichever way it went."},
{g:'How I work', id:'learn', q:'How do you learn a new domain?', k:'learn|new domain|unfamiliar|ramp up|pick up|steep',
 a:"From the source. When I joined a maritime project with no background in vessels, there was no handover, so I read the existing code, went out on the actual boat, studied the data and analyzed it until I understood how the system behaved. Within a year I was leading the team."},
{g:'How I work', id:'requirements', q:'How do you work with requirements and other teams?', k:'requirement|systems engineer|stakeholder|other teams|cross.?functional|document|specification|icd|interface control',
 a:"I start from the people who will use the system and write requirements as testable statements, then a design that traces back to them. Where my software meets another team's or another company's, I work to a written interface definition, so each side can develop separately and still fit together."},
{g:'How I work', id:'mistake', q:'What is a mistake you learned from?', k:'mistake|fail(ed|ure)?|went wrong|lesson|learned the hard way',
 a:"Early in my career, on a project with a very tight deadline, we skipped load testing and relied on an estimate. In production my component slowed to a halt at real volume, and the customer felt it. The lesson has stayed with me: an estimate is not a test. Since then I do not release without testing under realistic conditions, and where the real system is hard to test on, I build a way to test without it."},

/* ---------- the work ---------- */
{g:'My work', id:'satellite', q:'Tell me about your satellite work', k:'satellite|lynk|elveo|core network|gsm|lte|current (job|role|work|position)|what do you do now',
 a:"At Elveo Mobile I lead the core network software. With a colleague I designed and built its plugin architecture, which serves both satellite and ground, and I built the container builds and the release pipeline around it. Beyond that I keep to general terms, since the details belong to my employer."},
{g:'My work', id:'lynk', q:'What does Elveo Mobile do?', k:'what (does|is) (lynk|elveo)|elveo|omnispace|direct to (phone|cell|device)|sat(ellite)?.?to.?(phone|cell)|merger',
 a:"Elveo Mobile connects ordinary mobile phones directly to satellites, so a phone has coverage where there are no towers. It was formed in 2026 from the merger of Lynk Global, which I joined in 2023, and Omnispace. My part is the core network software: the part of a mobile network that knows who a subscriber is and routes their messages, running both on the satellites and on the ground."},
{g:'My work', id:'constraints', q:'What is different about software for satellites?', k:'constraint|different about|challenge|delay|latency|hard about',
 a:"The link. A satellite is overhead for a short time, the connection has long delays and can lose data, and you cannot easily reach the machine to look at it. So software for it has to be designed around bounded queues, timeouts and recovery, and around being able to tell what went wrong from very little information."},
{g:'My work', id:'devprod', q:'What is "one source for development and production"?', k:'one source|dev(elopment)? and prod|development environment|identical|same environment|dev container',
 a:"The development environment is built from the same container definitions as production, so what a developer runs is what ships, and a change made in development is the change that reaches production. It removes a whole class of problems that only appear after deployment."},
{g:'My work', id:'pipeline', q:'Tell me about the build and release work', k:'pipeline|ci\\/cd|\\bci\\b|docker|container|release|devops|build system|deploy',
 a:"A GitLab pipeline around container builds: unit tests and coverage, images built for two processor architectures, each build tagged as a release candidate, and promotion of the tested candidate to the official release. The release is the same artifact that was tested."},
{g:'My work', id:'operator', q:'Have you built operator tools or user interfaces?', k:'operator|user interface|\\bui\\b|gui|front.?end|dashboard|configuration (app|manager|tool)|fleet',
 a:"Yes. Qt applications for air traffic displays and for driving a vessel's systems during testing, and more recently internal operator tooling with a web front end, a REST back end, PostgreSQL and a command-line tool for automation. In my own product I built the whole app for web and phones."},
{g:'My work', id:'simulation', q:'What have you built for simulation?', k:'simulat|sitl|test(ing)? without|without (the )?(real )?(hardware|boat|vessel|network)|in the loop',
 a:"Yes, more than once. For a surface vessel, I built a playback simulator from recorded data, so use cases could run at a desk instead of at sea. More recently I introduced software-in-the-loop simulation for testing, set its design, and mentored the intern who built it. The principle is the same each time: when the real system is slow or costly to test on, build a way to test without it."},
{g:'My work', id:'playback', q:'How does a playback simulator work, and what are its limits?', k:'playback|replay|recorded data|limits? of',
 a:"It replays data recorded from the real system into the software, so the software receives exactly what it would receive in the field. It is accurate and quick to build. Its limit is that recorded data does not react: it cannot show how the vehicle would respond to a command. So it is right for testing how software handles its inputs, and anything that depends on the vehicle's response still has to be confirmed on the real thing."},
{g:'My work', id:'vessel', q:'Tell me about the vessel project', k:'vessel|maritime|boat|ship|gibbs|autonom|navigation|sea',
 a:"At Gibbs & Cox I worked on the proof-of-concept phase of an autonomous navigation system for surface vessels. I designed a Qt/C++ framework that models each onboard subsystem as a generic component behind a hardware abstraction, built a playback simulator for testing, and led a team of five software engineers. I keep the details general, as the work belongs to the customer."},
{g:'My work', id:'abstraction', q:'Give me an example of an abstraction you designed', k:'example of (an )?abstraction|hardware abstraction|engine|subsystem|generic component',
 a:"Take an engine. The abstraction defines what any engine can be asked to do: start, stop, throttle, reach a speed. A concrete class underneath speaks the protocol of the specific hardware. To support different hardware you write a new concrete class, and nothing above it changes."},
{g:'My work', id:'aviation', q:'Tell me about your aviation work', k:'aviation|faa|radar|ads-?b|l3|harris|surveillance|air traffic|drone|uav|unmanned|aircraft',
 a:"At L3Harris I worked on aviation surveillance: combining radar and ADS-B data from many sites in real time, air traffic display applications in Qt and C++, and applications for tracking unmanned aircraft. I also built a new surveillance system from scratch on a thread-pool framework, an approach the department later adopted across its projects. It was ground software about aircraft, not software on them."},
{g:'My work', id:'telecom', q:'What did you do in telecom?', k:'telecom|openet|billing|mediation|verizon|at&?t|sprint|carrier',
 a:"At Openet I built and supported mediation and billing platforms for carriers such as Verizon, AT&T and Sprint. High volume, production pressure, and a lot of diagnosis at customer sites: memory leaks, deadlocks and crashes, from first report to delivered patch."},
{g:'My work', id:'customer', q:'Tell me about solving a customer problem', k:'customer|client|support|production (issue|problem)|root cause|troubleshoot|debug',
 a:"A carrier's revenue reports showed a discrepancy they had been unable to explain for weeks. The data showed it began the day they added a new data stream of their own, which they were sure was not the cause. I respected that and kept following the evidence: one field in that stream had a slightly different format, and it exposed a bug in our own code. Their change had triggered it, but the defect was ours. I said so, fixed it and delivered a patch."},
{g:'My work', id:'debugging', q:'How do you debug hard problems?', k:'debug|crash|core dump|memory leak|deadlock|gdb|diagnos',
 a:"Start from evidence, not from a guess: logs, the data, a core dump with gdb. Reproduce the fault before fixing it, so the fix is aimed at something I can make happen on demand. And if a fix cannot be shown to address the cause, I take it out and keep looking, because an unproven fix hides the real problem."},

/* ---------- people ---------- */
{g:'Leading and mentoring', id:'lead', q:'Have you led a team?', k:'\\blead|team|manag|people|report(s|ing)? to|leadership',
 a:"Yes. At Gibbs & Cox I led five software engineers from customer requirements through deployment. In my current role I am the lead developer for the core network software, I take part in the team's hiring interviews, and I mentor."},
{g:'Leading and mentoring', id:'mentor', q:'How do you mentor engineers?', k:'mentor|intern|junior|coach|develop people|teach',
 a:"I give people real work that matches their ability, set the direction, and leave the details to them. With an intern last summer I provided the problem and the high-level design, checked in regularly, and guided him where knowledge of the system mattered. He delivered a project that is in use today. When someone brings me a problem, I ask what they have tried, and then explain the reasoning, not only the answer."},
{g:'Leading and mentoring', id:'hiring', q:'What do you look for when you interview engineers?', k:'hire|hiring|interview(ing)? (engineers|candidates)|look for in',
 a:"Real technical depth first: whether the person understands why something works, not only how to use it. And genuine interest in the work, someone who wants this job and is not just filling a position."},

/* ---------- skills ---------- */
{g:'Skills', id:'skills', q:'What are your strongest skills?', k:'skill|strength|good at|best at|expert|tools?\\b|tech(nolog)?|stack',
 a:"Architecture, above all: object-oriented design in C++, plugin frameworks, and keeping a core stable while features are added around it. Next to that, multithreading with thread and session pools, PostgreSQL and MongoDB, and the delivery side: Docker, GitLab CI/CD, GTest and GCov. I also build simulators so teams can test without the real hardware."},
{g:'Skills', id:'cpp', q:'How deep is your C++?', k:'c\\+\\+|cpp|modern c|stl|qt\\b',
 a:"C++ is my main language and has been throughout my career. I work in modern C++ on Linux: object-oriented design, the standard library, multithreading, shared libraries loaded at run time, and Qt for applications with a user interface. Most of what I have built is frameworks and services that other engineers write their code on top of."},
{g:'Skills', id:'languages', q:'Which programming languages do you use?', k:'language|java\\b|dart|flutter|sql',
 a:"C++ first. Java and PL/SQL from my years in telecom. Python for tooling and automation. SQL every day. And Dart with Flutter for application front ends, both at work and on my own product."},
{g:'Skills', id:'databases', q:'Which databases have you worked with?', k:'database|postgres|mongo|oracle|sqlite|\\bdb\\b|data model',
 a:"PostgreSQL and MongoDB in my current work, including data modeling and a generic session pool that puts both behind one interface. Oracle with PL/SQL at high volume in telecom billing. SQLite for embedded and test use."},
{g:'Skills', id:'python', q:'Python and web experience?', k:'python|web|react|angular|javascript|rest|api',
 a:"C++ is my main language. I use Python for tooling: command-line tools, test automation and scripts. For the web, I built an operator application with a Flutter front end and a REST back end with a written interface specification. I have not used React or Angular in production."},
{g:'Skills', id:'linux', q:'What is your experience with Linux and cloud?', k:'linux|unix|systemd|cloud|aws|cross.?compil|arm|architecture(s)? \\(|embedded linux',
 a:"All my server-side work is on Linux: services under systemd, shared libraries, cross-compilation for arm64 as well as amd64, and containers. On the cloud side I have deployed my own product on AWS with containers, a managed PostgreSQL database and object storage."},
{g:'Skills', id:'flight', q:'Do you do flight or embedded software?', k:'flight software|embedded|real.?time|kernel|firmware|driver|rtos',
 a:"No, and I would rather say so plainly. My depth is application and server-side software. My code runs alongside flight and embedded systems, so I design around their constraints, but I have not done hard real-time or kernel-level work. Where I add the most is the architecture above that layer."},

/* ---------- personal ---------- */
{g:'Personal', id:'space', q:'What interests you about space?', k:'space|rocket|launch|orbit|why satellite',
 a:"Watching it become practical in my own field. Connecting an ordinary phone to a satellite was not a viable business fifteen years ago; it is one now, because computing became far more capable for its weight and power and the cost of reaching orbit fell. Working on software that runs on satellites, and designing around what a satellite link can and cannot do, has been the most interesting engineering of my career."},
{g:'Personal', id:'yalabeena', q:'What is Yalabeena?', k:'yalabeena|personal|side project|own product|your product|booking|spare time|hobby|marketplace',
 a:"A marketplace for booking sessions with hosts such as teachers and coaches, which I designed, built and run by myself. Hosts publish calendars and rates; guests search, book and pay. It has family accounts, a cart and checkout, credit balances, refunds and statements, video sessions and chat inside the app, push notifications, an assistant, and an administration side. It is on the web and on phones, in English and Arabic."},
{g:'Personal', id:'yalastack', q:'How is Yalabeena built?', k:'yalabeena.*(built|stack|tech|architecture)|how is (it|your product) built|flutter app|drogon',
 also:['what technology does yalabeena use','what is the architecture of your product'],
 a:"One Flutter code base for the web, Android, iOS and desktop. The back end is C++ REST services built from plugin modules, the same way I build at work, on PostgreSQL with managed schema migrations. Payments by card and PayPal with reconciliation, video sessions and chat in real time, push notifications, scheduled jobs, and brand profiles so the same app can ship under another name."},
{g:'Personal', id:'yalatest', q:'How do you test and release your own product?', k:'yalabeena.*(test|release|deploy)|(test|release|deploy).*(your|own) (product|app)|(your|own) (product|app).*(test|release|deploy)|release candidate|app store|google play|end.?to.?end|e2e',
 a:"As strictly as at work. More than 200 end-to-end test files drive the real app across web, Android, iOS and desktop, alongside unit tests with coverage floors. A release goes out first as a release candidate to the web and back end, is proven there, and only then reaches the app stores. Structured logs, request tracing and incident reports tell me when something goes wrong."},
{g:'Personal', id:'yalaai', q:'Have you built anything with AI?', k:'\\bai\\b|assistant|llm|machine learning|language model|embedding|gpt',
 a:"Yes, in my own product. Its assistant answers from a bank of reviewed answers first: it matches a question by its words, then by its meaning, and a model confirms the match before the answer is shown. Only when nothing fits does the model answer on its own, and every answer is labeled with where it came from. I built it that way because a wrong answer about money or bookings costs more than no answer."},
{g:'Personal', id:'yalawhy', q:'Why do you run your own product?', k:'why (did you|do you) (build|run|make)|motivation|entrepreneur|founder|on your own',
 a:"Because it keeps me honest. At work I own the architecture; in my own product I own everything else too: what to build, the user's experience, payments, releases, support, and the consequences when something breaks at night. It has made me a better engineer at work, because I now feel what a design decision costs the person who has to operate it."},
{g:'Personal', id:'education', q:'What is your education?', k:'educat|degree|university|school|stud(y|ied)|nyu|master|bachelor|gpa',
 a:"An M.S. in Electrical Engineering from the NYU Tandon School of Engineering, with a GPA of 3.87, and a B.S. in Computer Engineering from Ain Shams University in Cairo."},
{g:'Personal', id:'location', q:'Where are you based?', k:'located|location|where (are|do) you|based|live|relocat|remote|time ?zone',
 a:"The Washington, D.C. area. For anything about location or availability, email me at wael.bahgat@gmail.com."},
{g:'Personal', id:'contact', q:'How can I contact you?', k:'contact|e-?mail|reach|get in touch|linkedin|resume|résumé|\\bcv\\b|phone',
 a:"By email at wael.bahgat@gmail.com, or on LinkedIn. My résumé is the PDF linked at the top of the page."},

/* ---------- about this page ---------- */
{g:'About this page', id:'site', q:'How was this page built?', k:'this (page|site|website)|built with|how (was|is) (this|it) (made|built)',
 a:"Plain HTML, CSS and a little JavaScript, with no framework and no server. The answers are a small list in a separate file, matched against your question by its words."}
];
